version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci
      - npx playwright install --with-deps

  build:
    commands:
      - npx playwright test

artifacts:
  files:
    - playwright-report/**/*
    - test-results/**/*